version: '3'

tasks:
  # When developing, compile and run
  run:
    cmds:
      - go run main.go --config examples/conf.yml
  # Release
  release:
    cmds:
      - |
        contrib/release --remote
  # Local build
  build:
    cmds:
      - |
        contrib/release --local
  # Print the change log
  changelog:
    cmds:
      - |
        jreleaser changelog && echo "Version: $JRELEASER_PROJECT_VERSION" && cat out/jreleaser/release/CHANGELOG.md
  # Install to test against a real config file
  install:
    cmds:
      - CGO_ENABLED=0 go install -ldflags="-X 'cmd.Version=$JRELEASER_PROJECT_VERSION'" mail-checker.go
